### ISSUE TITLE
latest pip fails to install zip:     ImportError: No module named req

### ISSUE THREAD

**Issue by mgheorghe** [kdheepak/zip#1]
on line 4 of setup .py there is this code
from pip.req import parse_requirements

pip internals should not be used this way and this fails with latest pip

do 
pip install --upgrade pip
pip install zip

upgrading pip to latest
Collecting pip
  Downloading https://files.pythonhosted.org/packages/5f/25/e52d3f31441505a5f3af41213346e5b6c221c9e086a166f3703d2ddaf940/pip-18.0-py2.py3-none-any.whl (1.3MB)
    100% |████████████████████████████████| 1.3MB 6.0MB/s
Installing collected packages: pip
  Found existing installation: pip 10.0.1
    Uninstalling pip-10.0.1:
      Successfully uninstalled pip-10.0.1
Successfully installed pip-18.0
.......
  Downloading https://files.pythonhosted.org/packages/b1/e7/212bf1ce8d65b357c337da56934922d18c3845127e8a188182266157c663/zip-0.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-d99V2P/zip/setup.py", line 4, in <module>
        from pip.req import parse_requirements
    ImportError: No module named req

**Comment by kdheepak** [comment]
Thanks for reporting. It seems `req` is deprecated. I'll fix this in the next release.

**Comment by kdheepak** [comment]
This should be resolved in the latest release.
